### ISSUE TITLE
preprocessed dataset

### ISSUE THREAD

**Issue by OxInsky1105** [jacob-thrasher/TE-SSL#1]
This work is excellent, but I encountered an issue while reproducing it. I found that the preprocessed dataset has inconsistencies, as the Clinica tool and the current ADNI format are not aligned. Could you kindly share your preprocessed ADNI dataset with me?

**Comment by jacob-thrasher** [comment]
Thank you for bringing this up. I also had trouble processing the data from the original paper (https://www.nature.com/articles/s41598-022-20674-x). I'd normally be happy to share my data, but in this case I worry that it would violate the ADNI terms. 

If you can elaborate more on the issue you are facing I'd be glad to try to help anyway.

**Comment by OxInsky1105** [comment]
Thank you very much! I have downloaded the ADNI1 1.5T MRI dataset, but it seems that the data I obtained is only post-processed data. There is a CSV file included, but it does not match the format required by Clinica.

Based on the files I currently have, it seems insufficient to convert the data into the format required by Clinica. Is there an alternative conversion pathway that I could use? Additionally, does this conversion process require Freesurfer and MATLAB software?

Thank you in advance for your help!

![image](https://github.com/user-attachments/assets/51106b2b-19fe-4ddb-9c92-232844a46fc5)
The tree structure of MR images
![image](https://github.com/user-attachments/assets/b8822720-8bf0-4b9d-8d6a-675be3ceb72c)
The clinica csv that I have
![image](https://github.com/user-attachments/assets/c0393f33-9362-498f-a5a4-27d46f3c2ce3)
The clinica information which contained in xml file 
 
so  how can i changed those to prepocessed data for this program.

**Comment by OxInsky1105** [comment]
> Thank you for bringing this up. I also had trouble processing the data from the original paper (https://www.nature.com/articles/s41598-022-20674-x). I'd normally be happy to share my data, but in this case I worry that it would violate the ADNI terms.
> 
> If you can elaborate more on the issue you are facing I'd be glad to try to help anyway.

I'm not entirely sure if sharing the processed data would violate ADNI's regulations, but I assure you it will only be used for research purposes and not for any commercial use. Thank you again!

**Comment by jacob-thrasher** [comment]
So I more or less just ended up using `adni_to_bids` ([link](https://aramislab.paris.inria.fr/clinica/docs/public/dev/#dataset-converters-clinica-convert)) to convert my data directory into BIDS format and then iterated through the BIDS directory and used 
`torchio.transforms.Resample` ([link](https://torchio.readthedocs.io/transforms/preprocessing.html#torchio.transforms.Resample)) to fit everything to the MNI template provided [[here](https://drive.google.com/file/d/1KurgyjQP-KReEO0gf31xxjwE5R-xuSRB/view)]. 

I found that Clinica was doing a lot of extra stuff that I didn't need and the original authors provided their MNI template, which let me register everything so that should be sufficient.

**Comment by OxInsky1105** [comment]
torchio.transforms.Resample maybe good. Thanks
